version: '3.8'
services:
  poller:
    build:
      context: .
      dockerfile: Dockerfile.poller
    restart: unless-stopped
    environment:
      # Required
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE=${SUPABASE_SERVICE_ROLE}
      # Optional
      - LIVE_SOURCE_URL=${LIVE_SOURCE_URL}
      - ADMIN_POLL_TOKEN=${ADMIN_POLL_TOKEN}
      - LIVE_POLL_INTERVAL_MS=${LIVE_POLL_INTERVAL_MS:-30000}
    healthcheck:
      test: ['CMD', 'test', '-f', '/app/cron/.last-poller-run']
      interval: 60s
      timeout: 5s
      retries: 3

