-- Custom types
create type public.user_role as enum ('fan', 'admin', 'athlete');
create type public.donation_target as enum ('OMVP', 'DMVP', 'TEAM');
create type public.content_type as enum ('video', 'image', 'text');
create type public.sentiment as enum ('positive', 'negative');

-- Users table
create table public.users (
  id uuid not null primary key default gen_random_uuid(),
  name text,
  email text not null unique,
  role user_role not null default 'fan'
);

-- Donations table
create table public.donations (
  id bigint generated by default as identity primary key,
  donor_name text,
  amount numeric not null,
  message text,
  target donation_target not null,
  week integer not null,
  is_public boolean default true not null,
  "timestamp" timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Athlete Responses table
create table public.athlete_responses (
  id bigint generated by default as identity primary key,
  role donation_target, -- OMVP or DMVP
  video_url text not null,
  caption text,
  week integer not null,
  uploaded_by uuid not null references public.users(id)
);

-- MVP Assignments table
create table public.mvp_assignments (
  week integer primary key,
  omvp_id uuid not null references public.users(id),
  dmvp_id uuid not null references public.users(id)
);

-- UGC Feed table
create table public.ugc_feed (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.users(id),
  content_type content_type not null,
  content_url text not null,
  sentiment sentiment,
  caption text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Polls table
create table public.polls (
  id bigint generated by default as identity primary key,
  question text not null,
  options jsonb not null,
  selected_option integer, -- index of the selected option in the options array
  ends_at timestamp with time zone
);
